package net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.ai

import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.SimpleGrammarOptionValues
import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.grammar.EOF
import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.grammar.FlexibleLiteralChoiceTerminal
import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.grammar.SequenceCombinator
import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.grammar.WhitespaceTerminal
import net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.optionvalues.grammar.ZeroOrMore

/*
 * [Link] NamePolicy= in a .link file.
 *
 * man    https://www.freedesktop.org/software/systemd/man/latest/systemd.link.html#NamePolicy=
 * parser https://github.com/systemd/systemd/blob/a8e93919c3/src/udev/net/link-config.c        config_parse_name_policy (DEFINE_CONFIG_PARSE_ENUMV)
 * values https://github.com/systemd/systemd/blob/a8e93919c3/src/shared/netif-naming-scheme.c  name_policy_table
 *
 * Distinct from AlternativeNamesPolicy=, which resolves against alternative_names_policy_table in the
 * same file and so offers neither "kernel" nor "keep".
 */

/**
 * Validator for `[Link] NamePolicy=` (.link).
 *
 * C function: config_parse_name_policy in src/udev/net/link-config.c, generated by
 * DEFINE_CONFIG_PARSE_ENUMV — a whitespace-separated list resolved through name_policy_table
 * (src/shared/netif-naming-scheme.c).
 *
 * Distinct from AlternativeNamesPolicy=, which uses alternative_names_policy_table and therefore does
 * not offer `kernel` or `keep`; see [ConfigParseAlternativeNamesPolicyOptionValue].
 */
class ConfigParseNamePolicyOptionValue : SimpleGrammarOptionValues(
    "config_parse_name_policy",
    SequenceCombinator(
        NAME_POLICY,
        ZeroOrMore(SequenceCombinator(WhitespaceTerminal(), NAME_POLICY)),
        EOF()
    )
) {
    companion object {
        private val NAME_POLICY = FlexibleLiteralChoiceTerminal(
            "kernel",
            "keep",
            "database",
            "onboard",
            "slot",
            "path",
            "mac",
        )
    }
}
