services:
  systemd-builder:
    build:
      context: .
      dockerfile: Systemd-Builder.Dockerfile
      args:
        BUILDDATE: "unset"
    volumes:
      - ./build:/mount/
  ubuntu-units-builder:
      build:
        context: .
        dockerfile: Ubuntu-Units.Dockerfile
      volumes:
        - ./build:/mount/
